### ISSUE TITLE
[PE-D][Tester C] Student name cut short

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F13-1/tp#162]
![image.png](https://raw.githubusercontent.com/eliotlee68/ped/main/files/abf60968-f3d3-459e-af02-9e86d4a922f4.png)

When viewing a student with a particularly long name, if the name does not fit in one line given the current window size, it it cut off with ellipses and there isn't a way to view the full name by scrolling or a display function, etc.

Steps to reproduce:
Add a student with ADDSTU with a very long name 
View the application in a windowed mode such that the name no longer fits in the viewing box.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: eliotlee68/ped#1

**Comment by tituschewxj** [comment]
Not a feature flaw. Is a functionality bug caused by extreme user behaviour: very long input values:

>Problems caused by very long input values: When a user input is unusually long e.g., a very long name, a very large number, it can cause problems e.g., the UI layout can get messed up, some part of it might get cut off.
>
>These can be considered cosmetic issues (i.e., severity.VeryLow) of type.FunctionalityBug.
However, if the problem can hinder the user (e.g., not seeing the last part of a very long name might not hinder the user but it does hinder the user if only the first few characters of the name is shown), the severity can be Low or higher. 

To prove that this is not in scope, we need to specific in the UG that it is not supported

>How to prove that something is response.NotInScope: In general, a flaw (e.g., a missing feature, a suboptimal design of a feature, a known bug) can be considered NotInScope if rectifying it is less important (based on the value/effort considerations) than the work that has been done already (because it is fine to delay lower priority work until future iterations).
>
>In addition, the following (at least one) need to be satisfied:
>* The UG specifies it as not supported or coming in a future version.
>* The user cannot attempt to use the missing feature or when the user does so, the software fails gracefully, possibly with a suitable error message i.e., the software should not crash.
>
>If a bug qualifies for response.NotInScope, the dev team will not be penalized, but the bug reporter will earn a small amount of credit for reporting it.

Todo:
- [ ] Add in the user guide that our application **does not support text wrapping** within the student contact list display panel, so long name will be cut off. It is less important, as names are not this long in reality, and not having the full name does not make it harder for a tutor to differentiate a student in the contact list.
