### ISSUE TITLE
[PE-D][Tester B] Editing of tags allow for duplicate tags under certain conditions

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F13-1/tp#205]
When running the command ```edit 1 t/ Friend t/ friend t/ Friends t/friends```, all 4 instance of tags are added as separate. 

Normally, when multiple tags are added, duplicates should be ignored. As such, there should be 2 tags saved, namely Friend and Friends (or can make all lower-case instead). 

However since the case is different, they are recorded as 4 separate tags instead. 

![image.png](https://raw.githubusercontent.com/azumieflare/ped/main/files/14a4d2c8-4e37-4325-827b-4f7a3342b61c.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: azumieflare/ped#13

**Comment by tituschewxj** [comment]
This is not a feature flaw. Since the tags are all different, they are not duplicates.

It is a documentation issue that we did not give enough details on tags.

Todo: add detail that tags are case sensitive, only distinct tags are stored, and tags have to be one word. Also the reasoning: tags are meant to be used by the user in any way they desire, so if a user wants to differentiate `LATE` from `late` they can. Why: In case the user wants to put more emphasize on a certain tag.

**Comment by belligerentbeagle** [comment]
> * add detail that tags are case sensitive, only distinct tags are stored, and tags have to be one word. See [[PE-D][Tester D] Functionality Bug: Tag field error in addstu command #169](https://github.com/AY2324S2-CS2103T-F13-1/tp/issues/169)

Resolved by PR #272  


> * [x]  Also the reasoning: tags are meant to be used by the user in any way they desire, so if a user wants to differentiate `LATE` from `late` they can. Why: In case the user wants to put more emphasize on a certain tag.
> * [x]  Also that tags are meant to use in any way a user desires, so if a user wants to store relationships, they can. Why? Every TA has their personalized choices and we respect that. See [[PE-D][Tester B] Tags for default value does not fit the context.  #206](https://github.com/AY2324S2-CS2103T-F13-1/tp/issues/206)
> *


Resolved by PR #271 in FAQ section
